"""Implementación de tabla source

Revision ID: 659df3252950
Revises: 6e5b164d1857
Create Date: 2026-04-20 14:22:15.060934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '659df3252950'
down_revision: Union[str, Sequence[str], None] = '6e5b164d1857'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('historical_data', sa.Column('source_id', sa.Integer(), nullable=True))
    op.alter_column('historical_data', 'value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=4),
               existing_nullable=True)
    op.create_foreign_key(None, 'historical_data', 'sources', ['source_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'historical_data', type_='foreignkey')
    op.alter_column('historical_data', 'value',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_column('historical_data', 'source_id')
    op.drop_table('sources')
    # ### end Alembic commands ###
